CREATE TABLE user (
    id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    childName VARCHAR(255) NOT NULL,
    childBirthday DATETIME NOT NULL,
    adhdDesc TEXT
);